server:
  port: 8083
spring:
  cloud:
    gateway:
      redis:
        enabled: false
      
      routes:
      - id: aml_auth
        uri: http://localhost:8084
        predicates:
        - Path=//aml/authentication
        filters:
        - TokenRelay=      
      - id: kyc_services
        uri: http://localhost:8085
        predicates:
        - Path=/aml/kyc/**
        filters:        - TokenRelay=
      - id: riskProfile_services
        uri: http://localhost:8086
        predicates:
        - Path=/aml/riskProfile/**
        filters:
        - TokenRelay=
      - id: unexpected_services
        uri: http://localhost:8087
        predicates:
        - Path=/aml/unexpected/**
        filters:
        - TokenRelay=

            
Comment: >     
  security:
    oauth2:
      client:        provider:          keycloak:
            issuer-uri: https://dev-55628242.okta.com/oauth2/default
        registration:          quotes-client:
            provider: keycloak
            client-id: 0oa72he7ux6u4HwNI5d7
            client-secret: JMbbGxcWmpCOY-sX1Gr3LlmhgwKYY1EQFF2yPQRs
            scope:            - email
            - profile
            - roles

          